FROM node:23-slim AS base

WORKDIR /app

RUN corepack enable pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

ARG PORT=3000
ENV PORT=$PORT

EXPOSE $PORT

CMD ["pnpm", "run", "start:dev"]
