services:
  streaming-api:
    container_name: streaming-api-container
    image: $REGISTRY_USER/streaming-api:latest
    pull_policy: always
    restart: always
    environment:
      PORT: 3000
    networks:
      - streaming-network
    ports:
      - 3000

  redis:
    image: redis:alpine
    container_name: streaming-redis
    ports:
      - '6379'
    networks:
      - streaming-network

networks:
  streaming-network:
    driver: bridge
