services:
  streaming-api-dev:
    container_name: streaming-api-dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    pull_policy: always
    restart: always
    environment:
      PORT: 3000
    networks:
      - streaming-network
    volumes:
      - .:/app
    ports:
      - 3000:3000

  redis:
    image: redis:alpine
    container_name: streaming-redis
    ports:
      - '6379'
    networks:
      - streaming-network

networks:
  streaming-network:
    driver: bridge
